(in-package :parseq)

(defrule terminal-t () t)
(defrule terminal-nil () nil)
(defrule terminal-symbol () 'a)
(defrule terminal-character () #\a)
(defrule terminal-string () "abc")
(defrule terminal-vector () #(1 2 3))
(defrule terminal-number () 5)
(defrule terminal-any-char () char)
(defrule terminal-any-stdchar () stdchar)
(defrule terminal-any-alpha () alpha)
(defrule terminal-any-digit () digit)
(defrule terminal-any-alphanumeric () alphanumeric)
(defrule terminal-any-byte () byte)
(defrule terminal-any-symbol () symbol)
(defrule terminal-any-keyword () keyword)
(defrule terminal-any-form () form)
(defrule terminal-any-atom () atom)
(defrule terminal-any-list () list)
(defrule terminal-any-cons () cons)
(defrule terminal-any-vector () vector)
(defrule terminal-any-number () number)
(defrule terminal-any-integer () integer)
(defrule terminal-any-string () string)
(defrule terminal-char-expr () (char "+a-zA-D7-9.;-"))

(defrule nonterminal-and () (and 'a 'b 'c))
(defrule nonterminal-and~ () (and~ 'a 'b 'c 'd))
(defrule nonterminal-and~~ () (and~~ (1 2 (1) (2 3)) 'a 'b 'c 'd))
(defrule nonterminal-and~~2 () (and~~ (* + ?) 'a 'b 'c))
(defrule nonterminal-or () (or 'a 'b 'c))
(defrule nonterminal-not () (not 'a))
(defrule nonterminal-* () (* 'a))
(defrule nonterminal-+ () (+ 'a))
(defrule nonterminal-? () (? 'a))
(defrule nonterminal-& () (& 'a))
(defrule nonterminal-! () (! 'a))
(defrule nonterminal-rep () (rep 4 'a))
(defrule nonterminal-rep-b () (rep (4) 'a))
(defrule nonterminal-rep-ab () (rep (3 5) 'a))
(defrule nonterminal-rep-nil-b () (rep (nil 5) 'a))
(defrule nonterminal-rep-a-nil () (rep (3 nil) 'a))
(defrule nonterminal-rep-nil-nil () (rep (nil nil) 'a))
(defrule nonterminal-rep-* () (rep * 'a))
(defrule nonterminal-rep-+ () (rep + 'a))
(defrule nonterminal-rep-? () (rep ? 'a))
(defrule nonterminal-list () (list 'a 'b))
(defrule nonterminal-string () (string #\a #\b))
(defrule nonterminal-vector () (vector 4 5))

(defrule parameter-terminal (x) x)
(defrule parameter-terminal-2 (x) x)
(defrule parameter-terminal-indirect () (parameter-terminal 'a))
(defrule parameter-repeat (x) (rep x 'a))
;; This is a convoluted test that uses nesting of nonterminals with parameters
(defrule parameter-slist (item sep) (and item (* (and sep item))))
(defrule parameter-slist-user-sep (y) (or 'b y))
(defrule parameter-slist-user (z) (parameter-slist 'a (parameter-slist-user-sep z)))
(defrule parameter-slist-user-user () (parameter-slist-user 'c))
(defrule parameter-constant (x) 'a (:constant x))
(defrule parameter-optional (&optional (x 5 x-p)) 'a (:constant (list x x-p)))
(defrule parameter-keyword (&key ((:x xx) 5 x-p)) 'a (:constant (list xx x-p)))
(defrule parameter-rest (&rest x) 'a (:constant x))

(defrule option-constant () (and 'a 'b 'c) (:constant 4))
(defrule option-lambda () (and 'a 'b 'c) (:lambda (x y z) (list z y x)))
(defrule option-lambda-rest () (and 'a 'b 'c) (:lambda (&rest items) (reverse items)))
(defrule option-destructure () (and (* 'a) 'b) (:destructure ((&rest a) b) `(,@a ,b)))
(defrule option-choose () (and 'a (* 'b) (rep 1 'c) (? (and (+ 'd) 'e)) 'f) (:choose 0 0 '(1 5) 2 '(3 1) '(3 0 0) -1 -10))
(defrule option-identity-t () (and 'a 'b 'c) (:identity t))
(defrule option-identity-n () (and 'a 'b 'c) (:identity nil))
(defrule option-flatten () (and (and 'a 'b) (and 'c 'd) (and 'e 'f)) (:flatten))
(defrule option-string () (and (and #\a "b") "cd" (and #\e #\f)) (:string))
(defrule option-string-symbol () (and (and #\a "b") "cd" (and #\e 'f)) (:string))
(defrule option-vector () (and (and 1 2) (and 3 4) (and 5 6)) (:vector))
(defrule option-test () number (:test (x) (= x 5)))
(defrule option-not () number (:not (x) (= x 5)))

(defrule multiopt-proc () number (:lambda (x) (1+ x)) (:lambda (x) (1+ x)))
(defrule multiopt-test-a () number (:test (x) (= x 5)) (:lambda (x) (1+ x)))
(defrule multiopt-test-b () number (:lambda (x) (1+ x)) (:test (x) (= x 5)))

(defrule bind-single () (and bind-single-number bind-single-repeat) (:let x))
(defrule bind-single-number () number (:external x) (:lambda (num) (setf x num)))
(defrule bind-single-repeat () (rep x 'a) (:external x))
(defrule bind-nest-number () number (:external x) (:lambda (num) (setf x num)))
(defrule bind-nest-repeat () (rep x bind-single) (:external x) )
(defrule bind-nest () (and bind-nest-number bind-nest-repeat) (:let x))

(defrule nest-or-and () (or (and 'a 'b) (and 'a 'c) (and 'd 'e)))
(defrule nest-and-or () (and (or 'a 'b) (or 'a 'c) (or 'd 'e)))
(defrule nest-*-and () (* (and 'a 'b)))
(defrule nest-and-* () (and (* 'a) (* 'b)))
(defrule nest-+-and () (+ (and 'a 'b)))
(defrule nest-and-+ () (and (+ 'a) (+ 'b)))
(defrule nest-list-list () (list (list 'a)))

(defrule parse-error () (and terminal-symbol (or (and 'b (* 'd) (parameter-terminal 'e)) (and 'c (or 'g 'h)) (and 'b 'f))))

(defrule recursion () (or (and 'a recursion) 'a))
(defrule left-recursion () (or (and 'a left-recursion 'b) (and left-recursion 'a) 'a))
(defrule left-recursion-indirect () (and (? 'b) left-recursion-indirect-2))
(defrule left-recursion-indirect-2 () (and (? 'b) left-recursion-indirect))

(defrule packrat-symbol () symbol (:packrat t))
(defrule packrat-symbol-user () (+ packrat-symbol))
(defrule packrat-a (a b c) 'a (:external x y z) (:constant (list a b c x y z)) (:packrat t))
(defrule packrat-b () 'b (:packrat t))
(defrule packrat-ab (a b c) (and (packrat-a a b c) packrat-b))
(defrule packrat-ab-2 (a b c) (and (packrat-a a b c) packrat-b) (:let (z 7)))
(defrule packrat-abc-1 () (or (and (packrat-ab 1 2 3) 'c) (packrat-ab 1 2 3)) (:let (x 4) (y 5) (z 6)))
(defrule packrat-abc-2 () (or (and (packrat-ab 1 2 3) 'c) (packrat-ab 1 2 4)) (:let (x 4) (y 5) (z 6)))
(defrule packrat-abc-3 () (or (and (packrat-ab 1 2 3) 'c) (packrat-ab-2 1 2 3)) (:let (x 4) (y 5) (z 6)))

(defrule loop-name () (and 'named symbol))
(defrule loop-iteration-with () (and 'with symbol '= form (* (and 'and symbol '= form))))
(defrule loop-iteration-up () (and (? (and (or 'from 'upfrom) form)) (? (and (or 'upto 'to 'below) form))))
(defrule loop-iteration-down1 () (and 'from form (or 'downto 'above) form))
(defrule loop-iteration-down2 () (and 'downfrom form (? (and (or 'downto 'to 'above) form))))
(defrule loop-iteration-numeric () (and (or loop-iteration-down1 loop-iteration-down2 loop-iteration-up) (? (and 'by form))))
(defrule loop-iteration-list () (and (or 'in 'on) form (? (and 'by form))))
(defrule loop-iteration-flex () (and '= form (? (and 'then form))))
(defrule loop-iteration-vector () (and 'across form))
(defrule loop-iteration-key () (and (or 'hash-key 'hash-keys) (or 'of 'in) form (? (and 'using (list (and 'hash-value symbol))))))
(defrule loop-iteration-value () (and (or 'hash-value 'hash-values) (or 'of 'in) form (? (and 'using (list (and 'hash-key symbol))))))
(defrule loop-iteration-package () (and (or 'symbol 'symbols 'present-symbol 'present-symbols 'external-symbol 'external-symbols) (or 'of 'in) form))
(defrule loop-iteration-hash () (and 'being (or 'the 'each) (or loop-iteration-key loop-iteration-value loop-iteration-package)))
(defrule loop-iteration-for-body () (or loop-iteration-list loop-iteration-flex loop-iteration-vector loop-iteration-hash loop-iteration-numeric))
(defrule loop-iteration-for () (and (or 'for 'as) symbol loop-iteration-for-body (* (and 'and symbol loop-iteration-for-body))))
(defrule loop-iteration () (or loop-iteration-with loop-iteration-for))
(defrule loop-around () (and (or 'initially 'finally) (+ (not loop-post-iteration))))
(defrule loop-repeat () (and 'repeat form))
(defrule loop-test () (and (or 'while 'until 'always 'never 'thereis) form))
(defrule loop-control () (or loop-around loop-repeat loop-test))
(defrule loop-do () (and (or 'do 'doing) (+ (not loop-post-iteration))))
(defrule loop-condition-and () (and loop-action (* (and 'and loop-action))))
(defrule loop-condition () (and (or 'if 'when 'unless) form loop-condition-and (? (and 'else loop-condition-and)) (? 'end)))
(defrule loop-return () (and 'return (or 'it form)))
(defrule loop-collect () (and (or 'collect 'collecting 'append 'appending 'nconc 'nconcing) (or 'it form) (? (and 'into form))))
(defrule loop-stat () (and (or 'count 'counting 'sum 'summing 'maximize 'maximizing 'minimize 'minimizing) (or 'it form) (? (and 'into form))))
(defrule loop-action () (or loop-do loop-condition loop-return loop-collect loop-stat)) ;; +
(defrule loop-post-iteration () (or loop-control loop-action))
(defrule loop () (and (? loop-name) (* loop-iteration) (* loop-post-iteration)))

(defrule url () (or url-generic url-httpaddress))
(defrule url-generic () (and url-scheme ":" url-path (? (and "?" url-search))))
(defrule url-scheme () url-ialpha (:string))
(defrule url-httpaddress () (and "http://" url-hostport (? (and #\/ url-path)) (? (and #\? url-search)))
  (:destructure (scheme (host port) path search)
                (list scheme
                      host
                      (if port (second port))
                      (if path (second path))
                      (if search (second search)))))
(defrule url-hostport () (and url-host (? (and #\: url-port))))
(defrule url-host () (or url-hostname url-hostnumber) (:string))
(defrule url-hostname () (and url-ialpha (? (and #\. url-hostname))))
(defrule url-hostnumber () (and url-digits #\. url-digits #\. url-digits #\. url-digits))
(defrule url-port () url-digits (:string) (:function #'parse-integer))
(defrule url-path () (and url-xpalphas (? (and #\/ url-path))) (:string))
(defrule url-search () (and url-xalphas (? (and #\+ url-search))) (:destructure (str more) (append (list str) (if more (second more)))))
(defrule url-xalpha () (or url-alpha url-digit url-safe url-extra url-escape))
(defrule url-xalphas () (+ url-xalpha) (:string))
(defrule url-xpalpha () (or url-xalpha #\+))
(defrule url-xpalphas () (+ url-xpalpha))
(defrule url-ialpha () (and url-alpha (? url-xalphas)))
(defrule url-alpha () char (:test (x) (alpha-char-p x)))
(defrule url-digit () char (:test (x) (digit-char-p x)))
(defrule url-digits () (+ url-digit))
(defrule url-safe () (or #\$ #\- #\_ #\@ #\. #\&))
(defrule url-extra () (or #\! #\* #\" #\' #\( #\) #\; #\, #\Space))
(defrule url-escape () (and #\% url-hex url-hex))
(defrule url-hex () (or url-digit #\a #\b #\c #\d #\e #\f #\A #\B #\C #\D #\E #\F))

;; ----- Helpers ----------------------------------------

(defun xnor (&rest forms)
  (evenp (count-if #'identity forms)))

(defun test-parseq (expression list &optional success (result nil result-p) junk-allowed (test #'equal))
  (multiple-value-bind (rslt success-p) (parseq expression list :junk-allowed junk-allowed)
    (and (xnor success success-p) (or (not result-p) (funcall test rslt result)))))

;; ----- Low level tests --------------------------------

(define-test treepos-test ()
  (check
    (equalp (make-treepos 1 2 3) #(1 2 3))
    (equalp (make-treepos) #(0))
    (condition= (make-treepos -1) error)
    (equalp (treepos-copy (make-treepos 1 2 3)) (make-treepos 1 2 3))
    (= (treepos-depth (make-treepos 1 2 3)) 3)
    (eql (treepos-valid (make-treepos 0) '()) nil)
    (eql (treepos-valid (make-treepos 0) '(a b)) t)
    (eql (treepos-valid (make-treepos 1) '(a b)) t)
    (eql (treepos-valid (make-treepos 2) '(a b)) nil)
    (eql (treepos-valid (make-treepos 0 0) '(a (b c))) nil)
    (eql (treepos-valid (make-treepos 1 0) '(a (b c))) t)
    (eql (treepos-valid (make-treepos 1 1) '(a (b c))) t)
    (eql (treepos-valid (make-treepos 1 2) '(a (b c))) nil)
    (eql (treepos-valid (make-treepos 2 0) '(a (b c))) nil)
    (equal (treeitem #() '(a b c d e)) '(a b c d e))
    (equal (treeitem (make-treepos) '(a b c d e)) 'a)
    (equal (treeitem (make-treepos 1 1) '(a (b b2) c d e)) 'b2)
    (condition= (treeitem (make-treepos 0 1) '(a (b b2) c d e)) error)
    (condition= (treeitem (make-treepos 1 2) '(a (b b2) c d e)) error)
    (= (treepos-length (make-treepos 1) '(a (b c) d)) 2)
    (condition= (treepos-length (make-treepos 0) '(a (b c) d)) generic-parse-error)
    (equalp (treepos-step (make-treepos 1)) (make-treepos 2))
    (equalp (treepos-step (make-treepos 1 2 3 4)) (make-treepos 1 2 3 5))
    (equalp (treepos-step-down (make-treepos 1)) (make-treepos 1 0))
    (equalp (treepos-step-down (make-treepos 1 2 3 4)) (make-treepos 1 2 3 4 0))
    (eql (treepos> (make-treepos 1) (make-treepos 1)) nil)
    (eql (treepos> (make-treepos 2) (make-treepos 1)) t)
    (eql (treepos> (make-treepos 1) (make-treepos 2)) nil)
    (eql (treepos> (make-treepos 1 2 3) (make-treepos 1 2 3)) nil)
    (eql (treepos> (make-treepos 1 2 4) (make-treepos 1 2 3)) t)
    (eql (treepos> (make-treepos 1 2 4) (make-treepos 1 3 3)) nil)
    (eql (treepos> (make-treepos 1 2 3) (make-treepos 1 2)) t)
    (eql (treepos> (make-treepos 1 2 3) (make-treepos 1 3)) nil)
    (eql (treepos> (make-treepos 1 3) (make-treepos 1 2 3)) t)
    (eql (treepos> (make-treepos 1 3) (make-treepos 1 3 3)) nil)
    (eql (treepos= (make-treepos 1 2 3) (make-treepos 1 2 3)) t)
    (eql (treepos= (make-treepos 1 2 3) (make-treepos 1 2 3 0)) nil)))

;; ----- High level tests -------------------------------

(define-test terminal-test ()
  (check
    (test-parseq 'terminal-t '(t) t t)
    (test-parseq 'terminal-t '(5) t 5)
    (test-parseq 'terminal-t '(nil) nil nil)
    (test-parseq 'terminal-nil '(nil) t nil)
    (test-parseq 'terminal-nil '(()) t nil)
    (test-parseq 'terminal-nil '(t) nil nil)
    (test-parseq 'terminal-symbol '(a) t 'a)
    (test-parseq 'terminal-symbol '(b) nil nil)
    (test-parseq 'terminal-symbol '(1) nil nil)
    (test-parseq 'terminal-character '(#\a) t #\a)
    (test-parseq 'terminal-character '(#\b) nil nil)
    (test-parseq 'terminal-character '(1) nil nil)
    (test-parseq 'terminal-string "abc" t "abc")
    (test-parseq 'terminal-string '("abc") t "abc")
    (test-parseq 'terminal-string '(1) nil nil)
    (test-parseq 'terminal-string "def" nil nil)
    (test-parseq 'terminal-vector #(1 2 3) t #(1 2 3) nil #'equalp)
    (test-parseq 'terminal-vector '(#(1 2 3)) t #(1 2 3) nil #'equalp)
    (test-parseq 'terminal-vector '((1 2 3)) nil nil)
    (test-parseq 'terminal-vector '("1 2 3") nil nil)
    (test-parseq 'terminal-vector #(4 5 6) nil nil #'equalp)
    (test-parseq 'terminal-number '(5) t 5)
    (test-parseq 'terminal-number '(4) nil nil)
    (test-parseq 'terminal-number '("abc") nil nil)
    (test-parseq 'terminal-any-char '(#\f) t #\f)
    (test-parseq 'terminal-any-char '(#\g) t #\g)
    (test-parseq 'terminal-any-char '(f) nil nil)
    (test-parseq 'terminal-any-stdchar '(#\f) t #\f)
    (test-parseq 'terminal-any-stdchar '(#\g) t #\g)
    (test-parseq 'terminal-any-stdchar '(#\Tab) nil nil)
    (test-parseq 'terminal-any-stdchar '(f) nil nil)
    (test-parseq 'terminal-any-alpha '(#\f) t #\f)
    (test-parseq 'terminal-any-alpha '(#\g) t #\g)
    (test-parseq 'terminal-any-alpha '(#\8) nil nil)
    (test-parseq 'terminal-any-alpha '(f) nil nil)
    (test-parseq 'terminal-any-digit '(#\7) t #\7)
    (test-parseq 'terminal-any-digit '(#\8) t #\8)
    (test-parseq 'terminal-any-digit '(#\f) nil nil)
    (test-parseq 'terminal-any-digit '(f) nil nil)
    (test-parseq 'terminal-any-alphanumeric '(#\f) t #\f)
    (test-parseq 'terminal-any-alphanumeric '(#\8) t #\8)
    (test-parseq 'terminal-any-alphanumeric '(#\Space) nil nil)
    (test-parseq 'terminal-any-alphanumeric '(f) nil nil)
    (test-parseq 'terminal-any-byte '(255) t 255)
    (test-parseq 'terminal-any-byte '(256) nil nil)
    (test-parseq 'terminal-any-byte '(0) t 0)
    (test-parseq 'terminal-any-byte '(-1) nil nil)
    (test-parseq 'terminal-any-byte '(a) nil nil)
    (test-parseq 'terminal-any-symbol '(f) t 'f)
    (test-parseq 'terminal-any-symbol '(#\f) nil nil)
    (test-parseq 'terminal-any-keyword '(:a) t :a)
    (test-parseq 'terminal-any-keyword '(a) nil nil)
    (test-parseq 'terminal-any-keyword '(#\a) nil nil)
    (test-parseq 'terminal-any-form '(nil) t nil)
    (test-parseq 'terminal-any-form '(#\a) t #\a)
    (test-parseq 'terminal-any-form '((foo)) t '(foo))
    (test-parseq 'terminal-any-atom '(nil) t nil)
    (test-parseq 'terminal-any-atom '(4) t 4)
    (test-parseq 'terminal-any-atom '((1 2)) nil nil)
    (test-parseq 'terminal-any-list '(nil) t nil)
    (test-parseq 'terminal-any-list '((+ 1 2)) t '(+ 1 2))
    (test-parseq 'terminal-any-list '(4) nil nil)
    (test-parseq 'terminal-any-cons '(nil) nil nil)
    (test-parseq 'terminal-any-cons '((1 . 2)) t '(1 . 2))
    (test-parseq 'terminal-any-cons '((1 2)) t '(1 2))
    (test-parseq 'terminal-any-cons '(4) nil nil)
    (test-parseq 'terminal-any-vector '(#(1 2)) t #(1 2) nil #'equalp)
    (test-parseq 'terminal-any-vector '(4) nil nil nil #'equalp)
    (test-parseq 'terminal-any-number '(4) t 4)
    (test-parseq 'terminal-any-number '(#\4) nil nil)
    (test-parseq 'terminal-any-integer '(4) t 4)
    (test-parseq 'terminal-any-integer '(4/5) nil nil)
    (test-parseq 'terminal-any-integer '(4.5) nil nil)
    (test-parseq 'terminal-any-integer '(#\4) nil nil)
    (test-parseq 'terminal-any-string '("foo") t "foo")
    (test-parseq 'terminal-any-string '(#\f) nil nil)
    ;; (char "+a-zA-D7-9.;-")
    (test-parseq 'terminal-char-expr "a" t #\a)
    (test-parseq 'terminal-char-expr "z" t #\z)
    (test-parseq 'terminal-char-expr "f" t #\f)
    (test-parseq 'terminal-char-expr "A" t #\A)
    (test-parseq 'terminal-char-expr "B" t #\B)
    (test-parseq 'terminal-char-expr "D" t #\D)
    (test-parseq 'terminal-char-expr "E" nil nil)
    (test-parseq 'terminal-char-expr "Z" nil nil)
    (test-parseq 'terminal-char-expr "0" nil nil)
    (test-parseq 'terminal-char-expr "6" nil nil)
    (test-parseq 'terminal-char-expr "7" t #\7)
    (test-parseq 'terminal-char-expr "8" t #\8)
    (test-parseq 'terminal-char-expr "9" t #\9)
    (test-parseq 'terminal-char-expr "." t #\.)
    (test-parseq 'terminal-char-expr ";" t #\;)
    (test-parseq 'terminal-char-expr "-" t #\-)
    (test-parseq 'terminal-char-expr "+" t #\+)
    (test-parseq 'terminal-char-expr "," nil nil)))

(define-test and-test ()
  (check
    ;; (and 'a 'b 'c)
    (test-parseq 'nonterminal-and '(a b c) t '(a b c))
    (test-parseq 'nonterminal-and '(a b) nil nil)
    (test-parseq 'nonterminal-and '(a c) nil nil)
    (test-parseq 'nonterminal-and '(a) nil nil)))

(define-test and~-test ()
  (check
    ;; (and~ 'a 'b 'c 'd)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d)) t '(a b c d))

    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c)) nil nil)

    (test-parseq 'nonterminal-and~ '(a b c d a) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)
    (test-parseq 'nonterminal-and~ (shuffle '(a b c d a)) nil nil)

    ;; (and~~ (1 2 (1) (2 3)) 'a 'b 'c 'd)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d)) t '((a) (b b) (c) (d d d)))

    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b d d)) t '((a) (b b) () (d d)))

    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a a b b c d d)) nil nil)

    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d)) nil nil)

    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)
    (test-parseq 'nonterminal-and~~ (shuffle '(a b b c d d d d)) nil nil)

    ;; (and~~ (* + ?) 'a 'b 'c)
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a a a b b b c)) t '((a a a) (b b b) (c)))

    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))
    (test-parseq 'nonterminal-and~~2 (shuffle '(b b b c)) t '(() (b b b) (c)))

    (test-parseq 'nonterminal-and~~2 (shuffle '(a b)) t '((a) (b) ()))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a b)) t '((a) (b) ()))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a b)) t '((a) (b) ()))
    (test-parseq 'nonterminal-and~~2 (shuffle '(a b)) t '((a) (b) ()))

    (test-parseq 'nonterminal-and~~2 (shuffle '(a)) nil nil)
    (test-parseq 'nonterminal-and~~2 (shuffle '(b c c)) nil nil)))

(define-test or-test ()
  (check
    ;; (or 'a 'b 'c)
    (test-parseq 'nonterminal-or '(a) t 'a)
    (test-parseq 'nonterminal-or '(b) t 'b)
    (test-parseq 'nonterminal-or '(c) t 'c)
    (test-parseq 'nonterminal-or '(d) nil nil)))

(define-test not-test ()
  (check
    ;; (not 'a)
    (test-parseq 'nonterminal-not '() nil nil)
    (test-parseq 'nonterminal-not '(a) nil nil)
    (test-parseq 'nonterminal-not '(b) t 'b)))

(define-test *-test ()
  (check
    ;; (* 'a)
    (test-parseq 'nonterminal-* '() t nil)
    (test-parseq 'nonterminal-* '(a) t '(a))
    (test-parseq 'nonterminal-* '(a a) t '(a a))
    (test-parseq 'nonterminal-* '(a a a) t '(a a a))
    (test-parseq 'nonterminal-* '(b) nil nil)
    (test-parseq 'nonterminal-* '(b) t nil t)
    (test-parseq 'nonterminal-* '(a b) nil nil)
    (test-parseq 'nonterminal-* '(a b) t '(a) t)))

(define-test +-test ()
  (check
    ;; (+ 'a)
    (test-parseq 'nonterminal-+ '() nil nil)
    (test-parseq 'nonterminal-+ '(a) t '(a))
    (test-parseq 'nonterminal-+ '(a a) t '(a a))
    (test-parseq 'nonterminal-+ '(a a a) t '(a a a))
    (test-parseq 'nonterminal-+ '(b) nil nil)
    (test-parseq 'nonterminal-+ '(a b) nil nil)
    (test-parseq 'nonterminal-+ '(a b) t '(a) t)))

(define-test ?-test ()
  (check
    ;; (? 'a)
    (test-parseq 'nonterminal-? '() t nil)
    (test-parseq 'nonterminal-? '(a) t 'a)
    (test-parseq 'nonterminal-? '(b) t nil t)))

(define-test &-test ()
  (check
    ;; (& 'a)
    (test-parseq 'nonterminal-& '(a) t 'a t)
    (test-parseq 'nonterminal-& '(b) nil nil t)))

(define-test !-test ()
  (check
    ;; (! 'a)
    (test-parseq 'nonterminal-! '() nil nil)
    (test-parseq 'nonterminal-! '(a) nil nil)
    (test-parseq 'nonterminal-! '(b) t 'b t)))

(define-test rep-test ()
  (check
    ;; (rep 4 'a)
    (test-parseq 'nonterminal-rep '() nil nil)
    (test-parseq 'nonterminal-rep '(a a a) nil nil)
    (test-parseq 'nonterminal-rep '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep '(a a a a a) nil nil)
    ;; (rep (4) 'a)
    (test-parseq 'nonterminal-rep-b '() t '())
    (test-parseq 'nonterminal-rep-b '(a) t '(a))
    (test-parseq 'nonterminal-rep-b '(a a) t '(a a))
    (test-parseq 'nonterminal-rep-b '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-b '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep-b '(a a a a a) nil nil)
    ;; (rep (nil 5) 'a)
    (test-parseq 'nonterminal-rep-nil-b '() t '())
    (test-parseq 'nonterminal-rep-nil-b '(a) t '(a))
    (test-parseq 'nonterminal-rep-nil-b '(a a) t '(a a))
    (test-parseq 'nonterminal-rep-nil-b '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-nil-b '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep-nil-b '(a a a a a) t '(a a a a a))
    (test-parseq 'nonterminal-rep-nil-b '(a a a a a a) nil nil)
    ;; (rep (3 5) 'a)
    (test-parseq 'nonterminal-rep-ab '(a a) nil nil)
    (test-parseq 'nonterminal-rep-ab '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-ab '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep-ab '(a a a a a) t '(a a a a a))
    (test-parseq 'nonterminal-rep-ab '(a a a a a a) nil nil)
    ;; (rep (3 nil) 'a)
    (test-parseq 'nonterminal-rep-a-nil '(a) nil nil)
    (test-parseq 'nonterminal-rep-a-nil '(a a) nil nil)
    (test-parseq 'nonterminal-rep-a-nil '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-a-nil '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep-a-nil '(a a a a a) t '(a a a a a))
    (test-parseq 'nonterminal-rep-a-nil '(a a a a a a) t '(a a a a a a))
    ;; (rep (nil nil) 'a)
    (test-parseq 'nonterminal-rep-nil-nil '() t '())
    (test-parseq 'nonterminal-rep-nil-nil '(a) t '(a))
    (test-parseq 'nonterminal-rep-nil-nil '(a a) t '(a a))
    (test-parseq 'nonterminal-rep-nil-nil '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-nil-nil '(a a a a) t '(a a a a))
    (test-parseq 'nonterminal-rep-nil-nil '(a a a a a) t '(a a a a a))
    (test-parseq 'nonterminal-rep-nil-nil '(a a a a a a) t '(a a a a a a))
    ;; (rep * 'a)
    (test-parseq 'nonterminal-rep-* '() t '())
    (test-parseq 'nonterminal-rep-* '(a) t '(a))
    (test-parseq 'nonterminal-rep-* '(a a) t '(a a))
    (test-parseq 'nonterminal-rep-* '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-* '(a a a a) t '(a a a a))
    ;; (rep + 'a)
    (test-parseq 'nonterminal-rep-+ '() nil nil)
    (test-parseq 'nonterminal-rep-+ '(a) t '(a))
    (test-parseq 'nonterminal-rep-+ '(a a) t '(a a))
    (test-parseq 'nonterminal-rep-+ '(a a a) t '(a a a))
    (test-parseq 'nonterminal-rep-+ '(a a a a) t '(a a a a))
    ;; (rep ? 'a)
    (test-parseq 'nonterminal-rep-? '() t '())
    (test-parseq 'nonterminal-rep-? '(a) t '(a))
    (test-parseq 'nonterminal-rep-? '(a a) nil nil)))

(define-test list-test ()
  (check
    ;; (list 'a)
    (test-parseq 'nonterminal-list '() nil nil)
    (test-parseq 'nonterminal-list '(a) nil nil)
    (test-parseq 'nonterminal-list '((a)) nil nil)
    (test-parseq 'nonterminal-list '((a b)) t '(a b))
    (test-parseq 'nonterminal-list '((a c)) nil nil)
    (test-parseq 'nonterminal-list '((b b)) nil nil)
    (test-parseq 'nonterminal-list '(#(a b)) nil nil)))

(define-test string-test ()
  (check
    ;; (string #\a)
    (test-parseq 'nonterminal-string '("") nil nil)
    (test-parseq 'nonterminal-string '("a") nil nil)
    (test-parseq 'nonterminal-string '("b") nil nil)
    (test-parseq 'nonterminal-string '("aa") nil nil)
    (test-parseq 'nonterminal-string '("ab") t '(#\a #\b))
    (test-parseq 'nonterminal-string '("bb") nil nil)
    (test-parseq 'nonterminal-string '((#\a #\b)) nil nil)))

(define-test string-type-test ()
  (check
    ;; These tests handle the subtle differences that led to the update of #'sequence=.
    ;; The update fixes every place that deals with strings (defrule too).
    ;; The observed specific types are enforced to guarantee test portability.
    (test-parseq 'terminal-string "abc" t "abc")
    (test-parseq 'terminal-string (coerce "abc" '(simple-array character (3))) t "abc")
    (test-parseq 'terminal-string (coerce "abc" '(simple-base-string 3)) t "abc")))

(define-test vector-test ()
  (check
    ;; (vector 4)
    (test-parseq 'nonterminal-vector '(#()) nil nil)
    (test-parseq 'nonterminal-vector '(#(3)) nil nil)
    (test-parseq 'nonterminal-vector '(#(4)) nil nil)
    (test-parseq 'nonterminal-vector '(#(4 4)) nil nil)
    (test-parseq 'nonterminal-vector '(#(4 5)) t '(4 5))
    (test-parseq 'nonterminal-vector '(#(5 5)) nil nil)
    (test-parseq 'nonterminal-vector '((4)) nil nil)))

(define-test parse-test ()
  (check
    ;; (vector 4)
    (condition= (parseq 'terminal-t '() :parse-error t) generic-parse-error)
    (condition= (parseq 'terminal-t '(1 2) :parse-error t) generic-parse-error)
    (= (parseq 'terminal-t '(1 2) :end 2 :parse-error t :junk-allowed t) 1)
    (condition= (parseq '(1 2) ()) invalid-rule-error)))

(define-test parameter-test ()
  (check
    ;; x
    (test-parseq '(parameter-terminal 'a) '(a) t 'a)
    (test-parseq '(parameter-terminal 'a) '(b) nil nil)
    (test-parseq '(parameter-terminal #\a) "a" t #\a)
    (test-parseq '(parameter-terminal #\a) "b" nil nil)
    (test-parseq '(parameter-terminal "abc") "abc" t "abc")
    (test-parseq '(parameter-terminal "abc") "def" nil nil)
    (test-parseq '(parameter-terminal "abc") '("abc") t "abc")
    (test-parseq '(parameter-terminal "abc") '("def") nil nil)
    (test-parseq '(parameter-terminal #(1 2 3)) #(1 2 3) t #(1 2 3) nil #'equalp)
    (test-parseq '(parameter-terminal #(1 2 3)) #(4 5 6) nil nil)
    (test-parseq '(parameter-terminal #(1 2 3)) '(#(1 2 3)) t #(1 2 3) nil #'equalp)
    (test-parseq '(parameter-terminal #(1 2 3)) '(#(4 5 6)) nil nil)
    (test-parseq '(parameter-terminal 5) '(5) t 5)
    (test-parseq '(parameter-terminal 5) '(6) nil nil)
    (test-parseq '(parameter-terminal terminal-t) '(1) t 1)
    (test-parseq '(parameter-terminal (parameter-terminal-2 'a)) '(a) t 'a)
    (condition= (parseq '(parameter-terminal #2A((3 4) (1 2))) '(a)) invalid-terminal-runtime-error)
    ;; (parameter-terminal 'a)
    (test-parseq 'parameter-terminal-indirect '(a) t 'a)
    ;; (rep x 'a))
    (test-parseq '(parameter-repeat 3) '(a a) nil nil)
    (test-parseq '(parameter-repeat 3) '(a a a) t '(a a a))
    (test-parseq '(parameter-repeat 3) '(a a a a) nil nil)
    ;; a b a b a b a
    (test-parseq '(parameter-slist-user-user) '(a) t '(a nil) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a) t '(a ((b a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a b a) t '(a ((b a) (b a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a b a b a) t '(a ((b a) (b a) (b a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a) t '(a ((b a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a c a) t '(a ((c a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a c a) t '(a ((b a) (c a))) nil)
    (test-parseq '(parameter-slist-user-user) '(a b a c a b a) t '(a ((b a) (c a) (b a))) nil)
    ;; 'a (:constant x)
    (test-parseq '(parameter-constant b) '(a) t 'b)))
    ;; Optional parameter
    (test-parseq 'parameter-optional '(a) t '(5 nil))
    (test-parseq '(parameter-optional) '(a) t '(5 nil))
    (test-parseq '(parameter-optional 1) '(a) t '(1 t))
    ;; Keyword parameter
    (test-parseq 'parameter-keyword '(a) t '(5 nil))
    (test-parseq '(parameter-keyword) '(a) t '(5 nil))
    (test-parseq '(parameter-keyword :x 1) '(a) t '(1 t))
    ;; Rest parameter
    (test-parseq 'parameter-rest '(a) t '())
    (test-parseq '(parameter-rest) '(a) t '())
    (test-parseq '(parameter-rest 1) '(a) t '(1))
    (test-parseq '(parameter-rest 1 2) '(a) t '(1 2))

(defrule in-brackets (x) (and "(" x ")"))
(defrule runtime-dispatch-literal-t () (in-brackets t))
(defrule runtime-dispatch-literal-nil () (in-brackets nil))
(defrule runtime-dispatch-specific-symbol () (in-brackets 'q))
(defrule runtime-dispatch-specific-character () (in-brackets #\q))
(defrule runtime-dispatch-specific-string () (in-brackets "test"))
(defrule runtime-dispatch-specific-vector () (in-brackets #(1 2 3)))
(defrule runtime-dispatch-specific-number () (in-brackets -4))
(defrule runtime-dispatch-character-set () (in-brackets (char "a-z")))
(defrule runtime-dispatch-any-character () (in-brackets char))
(defrule runtime-dispatch-any-standard-character () (in-brackets stdchar))
(defrule runtime-dispatch-any-alpha-character () (in-brackets alpha))
(defrule runtime-dispatch-any-digit-character () (in-brackets digit))
(defrule runtime-dispatch-any-alphanumeric-character () (in-brackets alphanumeric))
(defrule runtime-dispatch-any-byte () (in-brackets byte))
(defrule runtime-dispatch-any-symbol () (in-brackets symbol))
(defrule runtime-dispatch-any-keyword () (in-brackets keyword))
(defrule runtime-dispatch-any-form () (in-brackets form))
(defrule runtime-dispatch-any-atom () (in-brackets atom))
(defrule runtime-dispatch-any-list () (in-brackets list))
(defrule runtime-dispatch-any-cons () (in-brackets cons))
(defrule runtime-dispatch-any-vector () (in-brackets vector))
(defrule runtime-dispatch-any-number () (in-brackets number))
(defrule runtime-dispatch-any-integer () (in-brackets integer))
(defrule runtime-dispatch-any-string () (in-brackets string))

(define-test runtime-dispatch-test ()
  (check
    (test-parseq 'runtime-dispatch-literal-t '("(" t ")") t '("(" t ")"))
    (test-parseq 'runtime-dispatch-literal-t '("(" nil ")") nil nil)
    (test-parseq 'runtime-dispatch-literal-nil '("(" nil ")") t '("(" nil ")"))
    (test-parseq 'runtime-dispatch-literal-nil '("(" t ")") nil nil)
    (test-parseq 'runtime-dispatch-specific-symbol '("(" q ")") t '("(" q ")"))
    (test-parseq 'runtime-dispatch-specific-symbol '("(" p ")") nil nil)
    (test-parseq 'runtime-dispatch-specific-character '("(" #\q ")") t '("(" #\q ")"))
    (test-parseq 'runtime-dispatch-specific-character '("(" #\p ")") nil nil)
    (test-parseq 'runtime-dispatch-specific-string '("(" "test" ")") t '("(" "test" ")"))
    (test-parseq 'runtime-dispatch-specific-string '("(" "Test" ")") nil nil)
    (test-parseq 'runtime-dispatch-specific-string "(test)" t '("(" "test" ")"))
    (test-parseq 'runtime-dispatch-specific-string "(Test)" nil nil)
    (test-parseq 'runtime-dispatch-specific-vector #("(" 1 2 3 ")") t '("(" #(1 2 3) ")") :test #'equalp)
    (test-parseq 'runtime-dispatch-specific-vector #("(" 1 2 4 ")") nil nil :test #'equalp)
    (test-parseq 'runtime-dispatch-specific-vector '("(" #(1 2 3) ")") t '("(" #(1 2 3) ")") :test #'equalp)
    (test-parseq 'runtime-dispatch-specific-vector '("(" #(1 2 4) ")") nil nil :test #'equalp)
    (test-parseq 'runtime-dispatch-specific-number '("(" -4 ")") t '("(" -4 ")"))
    (test-parseq 'runtime-dispatch-specific-number '("(" +4 ")") nil nil)
    (test-parseq 'runtime-dispatch-character-set "(d)" t '("(" #\d ")"))
    (test-parseq 'runtime-dispatch-character-set "(5)" nil nil)
    (test-parseq 'runtime-dispatch-any-character "(d)" t '("(" #\d ")"))
    (test-parseq 'runtime-dispatch-any-character "(5)" t '("(" #\5 ")"))
    (test-parseq 'runtime-dispatch-any-alpha-character "(d)" t '("(" #\d ")"))
    (test-parseq 'runtime-dispatch-any-alpha-character "(5)" nil nil)
    (test-parseq 'runtime-dispatch-any-digit-character "(5)" t '("(" #\5 ")"))
    (test-parseq 'runtime-dispatch-any-digit-character "(d)" nil nil)
    (test-parseq 'runtime-dispatch-any-alphanumeric-character "(5)" t '("(" #\5 ")"))
    (test-parseq 'runtime-dispatch-any-alphanumeric-character "(d)" t '("(" #\d ")"))
    (test-parseq 'runtime-dispatch-any-alphanumeric-character "(.)" nil nil)
    (test-parseq 'runtime-dispatch-any-byte #("(" 255 ")") t '("(" 255 ")"))
    (test-parseq 'runtime-dispatch-any-byte #("(" 256 ")") nil nil)
    (test-parseq 'runtime-dispatch-any-byte #("(" 'x ")") nil nil)
    (test-parseq 'runtime-dispatch-any-symbol #("(" test ")") t '("(" test ")"))
    (test-parseq 'runtime-dispatch-any-symbol #("(" 3 ")") nil nil)
    (test-parseq 'runtime-dispatch-any-form #("(" test ")") t '("(" test ")"))
    (test-parseq 'runtime-dispatch-any-form #("(" nil ")") t '("(" nil ")"))
    (test-parseq 'runtime-dispatch-any-form #("(" ")") nil nil)))

(define-test option-test ()
  (check
    ;; (and 'a 'b 'c) (:constant 4)
    (test-parseq 'option-constant '(a b c) t 4)
    ;; (and 'a 'b 'c) (:lambda (x y z) (list z y x))
    (test-parseq 'option-lambda '(a b c) t '(c b a))
    ;; (and 'a 'b 'c) (:lambda (&rest items) (reverse items))
    (test-parseq 'option-lambda-rest '(a b c) t '(c b a))
    ;; (and (* 'a) 'b) (:destructure ((&rest a) b) `(,@a ,b))
    (test-parseq 'option-destructure '(a a a b) t '(a a a b))
    ;; (and 'a (* 'b) (rep 1 'c) (? (and (+ 'd) 'e)) 'f) (:choose 0 0 '(1 5) 2 '(3 1) '(3 0 0) -1 -10)
    (test-parseq 'option-choose '(a b c d e f) t '(a a nil (c) e d f nil))
    (test-parseq 'option-choose '(a b b b b b b b c d e f) t '(a a b (c) e d f nil))
    (test-parseq 'option-choose '(a c d e f) t '(a a nil (c) e d f nil))
    (test-parseq 'option-choose '(a b c f) t '(a a nil (c) nil nil f nil))
    ;; (and 'a 'b 'c) (:identity t)
    (test-parseq 'option-identity-t '(a b c) t '(a b c))
    ;; (and 'a 'b 'c) (:identity nil)
    (test-parseq 'option-identity-n '(a b c) t nil)
    ;; (and (and 'a 'b) (and 'c 'd) (and 'e 'f)) (:flatten)
    (test-parseq 'option-flatten '(a b c d e f) t '(a b c d e f))
    ;; (and (and #\a "b") "cd" (and #\e #\f)) (:string)
    (test-parseq 'option-string "abcdef" t "abcdef")
    (test-parseq 'option-string '(#\a "b" "cd" #\e #\f) t "abcdef")
    (test-parseq 'option-string #(#\a "b" "cd" #\e #\f) t "abcdef")
    ;; (and (and #\a "b") "cd" (and #\e 'f)) (:string)
    (test-parseq 'option-string-symbol '(#\a "b" "cd" #\e f) t "abcdeF")
    (test-parseq 'option-string-symbol #(#\a "b" "cd" #\e f) t "abcdeF")
    ;; (and (and 1 2) (and 3 4) (and 5 6)) (:vector)
    (test-parseq 'option-vector '(1 2 3 4 5 6) t #(1 2 3 4 5 6) nil #'equalp)
    (test-parseq 'option-vector #(1 2 3 4 5 6) t #(1 2 3 4 5 6) nil #'equalp)
    ;; number (:test (x) (= x 5))
    (test-parseq 'option-test '(4) nil nil)
    (test-parseq 'option-test '(5) t 5)
    (test-parseq 'option-test '(6) nil nil)
    ;; number (:not (x) (= x 5))
    (test-parseq 'option-not '(4) t 4)
    (test-parseq 'option-not '(5) nil nil)
    (test-parseq 'option-not '(6) t 6)))

(define-test multiopt-test ()
  (check
    ;; number (:lambda (x) (1+ x)) (:lambda (x) (1+ x)))
    (test-parseq 'multiopt-proc '(5) t 7)
    ;; number (:test (x) (= x 5)) (:lambda (x) (1+ x)))
    (test-parseq 'multiopt-test-a '(4) nil nil)
    (test-parseq 'multiopt-test-a '(5) t 6)
    ;; number (:lambda (x) (1+ x)) (:test (x) (= x 5)))
    (test-parseq 'multiopt-test-b '(4) t 5)
    (test-parseq 'multiopt-test-b '(5) nil nil)))

(define-test nesting-test ()
  (check
    ;; (or (and 'a 'b) (and 'a 'c) (and 'd 'e))
    (test-parseq 'nest-or-and '(a) nil nil)
    (test-parseq 'nest-or-and '(a b) t '(a b))
    (test-parseq 'nest-or-and '(a c) t '(a c))
    (test-parseq 'nest-or-and '(a e) nil nil)
    (test-parseq 'nest-or-and '(d) nil nil)
    (test-parseq 'nest-or-and '(d e) t '(d e))

    ;; (and (or 'a 'b) (or 'a 'c) (or 'd 'e))
    (test-parseq 'nest-and-or '(a) nil nil)
    (test-parseq 'nest-and-or '(b) nil nil)
    (test-parseq 'nest-and-or '(a a) nil nil)
    (test-parseq 'nest-and-or '(b a) nil nil)
    (test-parseq 'nest-and-or '(a c) nil nil)
    (test-parseq 'nest-and-or '(b c) nil nil)
    (test-parseq 'nest-and-or '(a a d) t '(a a d))
    (test-parseq 'nest-and-or '(b a d) t '(b a d))
    (test-parseq 'nest-and-or '(a c d) t '(a c d))
    (test-parseq 'nest-and-or '(b c d) t '(b c d))
    (test-parseq 'nest-and-or '(a a e) t '(a a e))
    (test-parseq 'nest-and-or '(b a e) t '(b a e))
    (test-parseq 'nest-and-or '(a c e) t '(a c e))
    (test-parseq 'nest-and-or '(b c e) t '(b c e))

    ;; (* (and 'a 'b))
    (test-parseq 'nest-*-and '() t nil)
    (test-parseq 'nest-*-and '(a) nil nil)
    (test-parseq 'nest-*-and '(a) t nil t)
    (test-parseq 'nest-*-and '(a b) t)
    (test-parseq 'nest-*-and '(a b a) nil nil)
    (test-parseq 'nest-*-and '(a b a) t '((a b)) t)
    (test-parseq 'nest-*-and '(a b a b) t)

    ;; (and (* 'a 'b))
    (test-parseq 'nest-and-* '() t '(nil nil))
    (test-parseq 'nest-and-* '(a) t '((a) nil))
    (test-parseq 'nest-and-* '(a a) t '((a a) nil))
    (test-parseq 'nest-and-* '(b) t '(nil (b)))
    (test-parseq 'nest-and-* '(b b) t '(nil (b b)))
    (test-parseq 'nest-and-* '(a b) t '((a) (b)))
    (test-parseq 'nest-and-* '(a a b) t '((a a) (b)))
    (test-parseq 'nest-and-* '(a b b) t '((a) (b b)))

    ;; (+ (and 'a 'b))
    (test-parseq 'nest-+-and '() nil nil)
    (test-parseq 'nest-+-and '(a) nil nil)
    (test-parseq 'nest-+-and '(a b) t '((a b)))
    (test-parseq 'nest-+-and '(a b a) nil)
    (test-parseq 'nest-+-and '(a b a) t '((a b)) t)
    (test-parseq 'nest-+-and '(a b a b) t '((a b) (a b)))

    ;; (and (+ 'a 'b))
    (test-parseq 'nest-and-+ '() nil nil)
    (test-parseq 'nest-and-+ '(a) nil nil)
    (test-parseq 'nest-and-+ '(a a) nil nil)
    (test-parseq 'nest-and-+ '(b) nil nil)
    (test-parseq 'nest-and-+ '(b b) nil nil)
    (test-parseq 'nest-and-+ '(a b) t '((a) (b)))
    (test-parseq 'nest-and-+ '(a a b) t '((a a) (b)))
    (test-parseq 'nest-and-+ '(a b b) t '((a) (b b)))

    (test-parseq 'nest-list-list '(((a))) t '((a)))))

(define-test bind-test ()
  (check
    (test-parseq 'bind-single '(4 a a a) nil nil)
    (test-parseq 'bind-single '(4 a a a a) t '(4 (a a a a)))
    (test-parseq 'bind-single '(4 a a a a a) nil nil)
    (test-parseq 'bind-nest '(3 3 a a a 2 a a 7 a a a a a a a 1 a) nil nil)
    (test-parseq 'bind-nest '(4 3 a a a 2 a a 7 a a a a a a a 1 a) t '(4 ((3 (a a a)) (2 (a a)) (7 (a a a a a a a)) (1 (a)))))
    (test-parseq 'bind-nest '(5 3 a a a 2 a a 7 a a a a a a a 1 a) nil nil)
    (test-parseq 'bind-nest '(4 3 a a a 2 a a 6 a a a a a a a 1 a) nil nil)
    (test-parseq 'bind-nest '(4 3 a a a 2 a a 8 a a a a a a a 1 a) nil nil)))

(define-test namespace-test ()
  (check-with-side-effects
    ;; Sanity check
    (test-parseq 'nonterminal-and '(a b c) t '(a b c))
    ;; Local rules
    (with-local-rules
      (condition= (parseq 'nonterminal-and '(a b c)) unknown-rule-error))
    (with-local-rules
      (defrule nonterminal-and () (and 'd 'e 'f))
      (test-parseq 'nonterminal-and '(a b c) nil nil))
    (with-local-rules
      (defrule nonterminal-and () (and 'd 'e 'f))
      (test-parseq 'nonterminal-and '(d e f) t '(d e f)))
    ;; Saved rules
    (with-saved-rules
      (test-parseq 'nonterminal-and '(a b c) t '(a b c)))
    (with-saved-rules
      (defrule nonterminal-and () (and 'd 'e 'f))
      (test-parseq 'nonterminal-and '(d e f) t '(d e f)))
    ;; Clear rules
    (with-saved-rules
      (test-parseq 'nonterminal-and '(a b c) t '(a b c))
      (clear-rules)
      (condition= (parseq 'nonterminal-and '(a b c)) unknown-rule-error)
      (defrule nonterminal-and () (and 'd 'e 'f))
      (test-parseq 'nonterminal-and '(d e f) t '(d e f)))
    ;; Sanity check
    (test-parseq 'nonterminal-and '(a b c) t '(a b c))
    (test-parseq 'nonterminal-and '(d e f) nil nil)))

(define-test parse-error-test ()
  (check
    ;; parse-match-error
    ;; (and terminal-symbol (or (and 'b (* 'd) (parameter-terminal 'e)) (and 'c (or 'g 'h)) (and 'b 'f)))
    (condition= (parseq 'parse-error '(v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 0)) (equal (parse-error-terminals obj) '('a)))
    (condition= (parseq 'parse-error '(a v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 1)) (equal (parse-error-terminals obj) '('b 'c)))
    (condition= (parseq 'parse-error '(a b v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 2)) (equal (parse-error-terminals obj) '('d 'e 'f)))
    (condition= (parseq 'parse-error '(a c v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 2)) (equal (parse-error-terminals obj) '('g 'h)))
    (condition= (parseq 'parse-error '(a b d v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 3)) (equal (parse-error-terminals obj) '('d 'e)))
    (condition= (parseq 'parse-error '(a b d d v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 4)) (equal (parse-error-terminals obj) '('d 'e)))
    (condition= (parseq 'parse-error '(a b d d d v) :parse-error t) parse-match-error obj (treepos= (parse-error-position obj) (make-treepos 5)) (equal (parse-error-terminals obj) '('d 'e)))
    ;; parse-junk-error
    (condition= (parseq 'parse-error '(a b f v) :parse-error t) parse-junk-error)))

(define-test recursion-test ()
  (check
    (test-parseq 'recursion '() nil nil)
    (test-parseq 'recursion '(a) t 'a)
    (test-parseq 'recursion '(a a) t '(a a))
    (test-parseq 'recursion '(a a a) t '(a (a a)))
    (test-parseq 'recursion '(a a a a) t '(a (a (a a))))
    (test-parseq 'recursion '(a a a a a) t '(a (a (a (a a)))))))

(define-test left-recursion-test ()
  (check
    (condition= (parseq 'left-recursion-indirect '(a a a)) left-recursion-error)
    (condition= (parseq 'left-recursion '(a a a)) left-recursion-error)))

(define-test packrat-test ()
  (check
    (test-parseq 'packrat-symbol-user '(a b c) t '(a b c))
    (test-parseq 'packrat-abc-1 '(a b) t '((1 2 3 4 5 6) b))
    (test-parseq 'packrat-abc-2 '(a b) t '((1 2 4 4 5 6) b))
    (test-parseq 'packrat-abc-3 '(a b) t '((1 2 3 4 5 7) b))))

(define-test loop-test ()
  (check
    (test-parseq 'loop '(named q for a from 0 below 10 by 10) t)
    (test-parseq 'loop '(named q for a from 0 above -10 by 10) t)
    (test-parseq 'loop '(named q for a downfrom 0 above 10 by 10) t)
    (test-parseq 'loop '(named q for a in lst by #'cdr) t)
    (test-parseq 'loop '(named q for a = 0 then (1+ a)) t)
    (test-parseq 'loop '(named q for a across vec) t)
    (test-parseq 'loop '(named q for k being the hash-key of (hsh) using (hash-value v)) t)
    (test-parseq 'loop '(named q for v being the hash-value of (hsh) using (hash-key v)) t)
    (test-parseq 'loop '(named q for k being the external-symbol of (pkg)) t)
    (test-parseq 'loop '(for i in lst initially a b c while d) t)
    (test-parseq 'loop '(for i in list repeat 5) t)
    (test-parseq 'loop '(for i in list thereis (> i 0)) t)
    (test-parseq 'loop '(for i across vec when (> i 0) collecting it into q and summing i into n else maximize i into m and return 5 end) t)
    (test-parseq 'loop '(for i across vec unless (minusp i) count i into q) t)))

(define-test url-test ()
  (check
    (test-parseq 'url "http://github.com:22/mrossini-ethz/parseq?foo+bar+baz" t '("http://" "github.com" 22 "mrossini-ethz/parseq" ("foo" "bar" "baz")))))

(define-test parseq-test ()
  (check
    (treepos-test)
    (terminal-test)
    (and-test)
    (and~-test)
    (or-test)
    (not-test)
    (*-test)
    (+-test)
    (?-test)
    (&-test)
    (!-test)
    (rep-test)
    (list-test)
    (string-test)
    (string-type-test)
    (vector-test)
    (parse-test)
    (parameter-test)
    (runtime-dispatch-test)
    (option-test)
    (multiopt-test)
    (nesting-test)
    (bind-test)
    (namespace-test)
    (parse-error-test)
    (recursion-test)
    (left-recursion-test)
    (packrat-test)
    (loop-test)
    (url-test)))
